source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'ios-app' do
  # MultiPlatformLibrary
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
  pod 'MultiPlatformLibrarySwift', :path => '../mpp-library'

  target :Tests
end

target 'pods-test' do
  pod 'mpp_library_pods', :path => '../mpp-library-pods'
  pod 'mpp_library_podsSwift', :path => '../mpp-library-pods'
end
